name: Pull Request CI

on:
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 🔐 Set up permission
        run: chmod +x gradlew
      - name: 🔨 Build debug
        run: ./gradlew assembleDebug
      - name: 🛠️ Unit-test
        run: ./gradlew test
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 💙 Ktlint
        run: ./gradlew ktlintCheck
      - name: 💜 Detekt
        run: ./gradlew detekt
  check_aseemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 🔐 Set up permission
        run: chmod +x gradlew
      - name: 🔨 Build internal release
        run: ./gradlew assembleDebug
      - name: 🔄 Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: App.apk
          path: app/build/outputs/apk/debug/app-debug.apk
  idea_cli_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lionzxy/idea-cli-inspector-actions@v1
        name: 💡 Check with IDEA CLI Inspector
